#!/bin/sh
# RAL test build packaging script
mvn package
rm -f ral.zip
cd target
zip ../ral.zip cdsp-ral-0.666-SNAPSHOT.jar
cd ../docs
asciidoctor-pdf full.adoc -o full.pdf
cd ..
zip ral.zip -r docs/full.pdf include

