#!/bin/sh
# RAL test build packaging script
mvn package
rm -f ral.zip
cp target/cdsp-ral-0.666-SNAPSHOT-jar-with-dependencies.jar ral.jar
zip ral.zip ral.jar ral
java -jar ral.jar docGen docs/all.ral docs/Library/gen.adoc +std/ -std/compiler_helpers.ral
cd docs
asciidoctor-pdf full.adoc -o ../manual.pdf
cd ..
zip ral.zip -r manual.pdf include/std syntax
