[package]
name = "s16tool"
version = "0.1.0"
edition = "2015"

[dependencies]
image = "0.24.9"
libkc3ds = { path = "../libkc3ds", version = "0.1.0"}
norncli = { path = "../norncli", version = "0.1.0"}
