#!/bin/sh
# RAL build script
(cd .. ; mvn install) || exit
mvn package || exit
# FOR LATER
#cd .. || exit
#./java-package-all || exit
#cd ral || exit
cp target/cdsp-ral-0.666-SNAPSHOT-jar-with-dependencies.jar ral.jar || exit

