#!/bin/sh
cd docs
rm ../manual-html/*.html
echo Manual: Compiling
for SECTION_FILE in `ls by-section | grep adoc`; do
	asciidoctor -a data-uri -b html by-section/$SECTION_FILE -o ../manual-html/`basename -s .adoc $SECTION_FILE`.html || exit
done
echo Manual: Done compiling

