#!/bin/sh
rm -rf "local/"

mkdir -p "local/Backgrounds"
mkdir -p "local/Body Data"
mkdir -p "local/Bootstrap"
mkdir -p "local/Catalogue"
mkdir -p "local/My Creatures"
mkdir -p "local/Genetics"
mkdir -p "local/Images"
mkdir -p "local/Overlay Data"
mkdir -p "local/My Agents"
mkdir -p "local/Sounds"

mkdir -p "local/Creature Galleries"
mkdir -p "local/Journal"
mkdir -p "local/My Worlds"
mkdir -p "local/Users"

echo "# Dummy" > "local/Catalogue/nucleus_dummy.catalogue"
mkdir -p "local/Bootstrap/000 Switcher"

cp "ds/Bootstrap/000 Switcher/!DS splash map.cos" "local/Bootstrap/000 Switcher"
cp "ds/Bootstrap/010 Docking Station/DS CAOS command line.cos" "local/Bootstrap/000 Switcher"

cp machine-nucleus.cfg machine.cfg
cp user-nucleus.cfg user.cfg
