# from https://github.com/rust-lang/mdBook/wiki/Automated-Deployment:-GitHub-Actions
# with minor modifications

name: Deploy
on:
  push:
    branches:
      - pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # To push a branch
      pages: write  # To push to a GitHub Pages site
      id-token: write # To update the deployment status
    steps:
      # setup phase
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install latest mdbook
        run: |
          url="https://github.com/rust-lang/mdbook/releases/download/v0.5.2/mdbook-v0.5.2-x86_64-unknown-linux-gnu.tar.gz"
          mkdir mdbook-bin
          curl -sSL $url | tar -xz --directory=./mdbook-bin
          echo `pwd`/mdbook-bin >> $GITHUB_PATH
      # gen phase
      - name: Build Site
        run: |
          ./build-site
      # submit phase
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'site'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
